-- =============================================================================
-- GoodSale Marketplace — Complete Supabase PostgreSQL Schema
-- Runnable migration: tables, helpers, RLS, triggers, realtime, seeds
-- =============================================================================

-- Storage buckets (create via Dashboard or Storage API; documented here only):
--   government-ids  — private — identity verification document uploads
--   product-images  — public  — marketplace product photos
--   chat-media      — public  — chat images, video, voice notes

CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- =============================================================================
-- SHARED TRIGGER HELPER
-- =============================================================================

CREATE OR REPLACE FUNCTION public.set_updated_at()
RETURNS trigger
LANGUAGE plpgsql
AS $$
BEGIN
  NEW.updated_at = now();
  RETURN NEW;
END;
$$;

-- =============================================================================
-- PROFILES (User + Profile merged; bigint PK for TS number ids)
-- =============================================================================

CREATE TABLE public.profiles (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  auth_id uuid UNIQUE NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  full_name text NOT NULL DEFAULT '',
  username text UNIQUE NOT NULL,
  email text NOT NULL DEFAULT '',
  phone_number text NOT NULL DEFAULT '',
  role text NOT NULL DEFAULT 'BUYER',
  referral_code text,
  referred_by_id bigint REFERENCES public.profiles(id) ON DELETE SET NULL,
  trust_score numeric NOT NULL DEFAULT 50,
  seller_level text NOT NULL DEFAULT 'BRONZE',
  good_points integer NOT NULL DEFAULT 0,
  is_suspended boolean NOT NULL DEFAULT false,
  photo_url text NOT NULL DEFAULT '',
  cover_url text NOT NULL DEFAULT '',
  bio text NOT NULL DEFAULT '',
  address text NOT NULL DEFAULT '',
  city text NOT NULL DEFAULT '',
  state text NOT NULL DEFAULT '',
  lat double precision,
  lng double precision,
  delivery_preference text NOT NULL DEFAULT '',
  push_enabled boolean NOT NULL DEFAULT true,
  email_enabled boolean NOT NULL DEFAULT true,
  sms_enabled boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_profiles_auth_id ON public.profiles(auth_id);
CREATE INDEX idx_profiles_username ON public.profiles(username);
CREATE INDEX idx_profiles_role ON public.profiles(role);
CREATE INDEX idx_profiles_referred_by_id ON public.profiles(referred_by_id);
CREATE INDEX idx_profiles_referral_code ON public.profiles(referral_code);

CREATE TRIGGER profiles_set_updated_at
  BEFORE UPDATE ON public.profiles
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- =============================================================================
-- PROFILE HELPERS (depend on profiles table)
-- =============================================================================

CREATE OR REPLACE FUNCTION public.current_profile_id()
RETURNS bigint
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT id FROM public.profiles WHERE auth_id = auth.uid() LIMIT 1;
$$;

CREATE OR REPLACE FUNCTION public.is_admin()
RETURNS boolean
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.profiles
    WHERE auth_id = auth.uid()
      AND role IN ('ADMIN', 'SUPER_ADMIN')
  );
$$;

-- Auto-create profile on auth signup
CREATE OR REPLACE FUNCTION public.handle_new_user()
RETURNS trigger
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  meta_full_name text;
  meta_username text;
  meta_phone text;
  meta_role text;
  base_username text;
  final_username text;
  suffix int := 0;
BEGIN
  meta_full_name := COALESCE(NEW.raw_user_meta_data->>'full_name', NEW.raw_user_meta_data->>'fullName', '');
  meta_username := COALESCE(NEW.raw_user_meta_data->>'username', '');
  meta_phone := COALESCE(
    NEW.raw_user_meta_data->>'phone',
    NEW.raw_user_meta_data->>'phone_number',
    NEW.raw_user_meta_data->>'phoneNumber',
    ''
  );
  meta_role := upper(COALESCE(NEW.raw_user_meta_data->>'role', 'BUYER'));
  IF meta_role NOT IN ('BUYER', 'SELLER', 'BUSINESS') THEN
    meta_role := 'BUYER';
  END IF;

  IF meta_username = '' OR meta_username IS NULL THEN
    base_username := lower(regexp_replace(split_part(COALESCE(NEW.email, 'user'), '@', 1), '[^a-zA-Z0-9_]', '', 'g'));
    IF base_username = '' THEN
      base_username := 'user';
    END IF;
  ELSE
    base_username := lower(regexp_replace(meta_username, '[^a-zA-Z0-9_]', '', 'g'));
  END IF;

  final_username := base_username;
  WHILE EXISTS (SELECT 1 FROM public.profiles WHERE username = final_username) LOOP
    suffix := suffix + 1;
    final_username := base_username || suffix::text;
  END LOOP;

  INSERT INTO public.profiles (
    auth_id,
    full_name,
    username,
    email,
    phone_number,
    role,
    referral_code
  ) VALUES (
    NEW.id,
    meta_full_name,
    final_username,
    COALESCE(NEW.email, ''),
    meta_phone,
    meta_role,
    'GS-' || upper(left(final_username, 8)) || '-' || lpad((floor(random() * 100))::int::text, 2, '0')
  );

  RETURN NEW;
END;
$$;

DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
CREATE TRIGGER on_auth_user_created
  AFTER INSERT ON auth.users
  FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();

-- =============================================================================
-- BUSINESSES
-- =============================================================================

CREATE TABLE public.businesses (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  owner_id bigint NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  name text NOT NULL,
  logo_url text NOT NULL DEFAULT '',
  banner_url text NOT NULL DEFAULT '',
  description text NOT NULL DEFAULT '',
  opening_hours text NOT NULL DEFAULT '',
  address text NOT NULL DEFAULT '',
  city text NOT NULL DEFAULT '',
  state text NOT NULL DEFAULT '',
  is_verified boolean NOT NULL DEFAULT false,
  trust_score numeric NOT NULL DEFAULT 50,
  followers integer NOT NULL DEFAULT 0,
  rating numeric NOT NULL DEFAULT 0,
  reviews_count integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_businesses_owner_id ON public.businesses(owner_id);
CREATE INDEX idx_businesses_city ON public.businesses(city);
CREATE INDEX idx_businesses_is_verified ON public.businesses(is_verified);

CREATE TRIGGER businesses_set_updated_at
  BEFORE UPDATE ON public.businesses
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- =============================================================================
-- PRODUCTS
-- =============================================================================

CREATE TABLE public.products (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  seller_id bigint NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  business_id bigint REFERENCES public.businesses(id) ON DELETE SET NULL,
  title text NOT NULL,
  description text NOT NULL DEFAULT '',
  category text NOT NULL DEFAULT '',
  brand text NOT NULL DEFAULT '',
  condition text NOT NULL DEFAULT 'GOOD',
  price numeric NOT NULL DEFAULT 0,
  is_negotiable boolean NOT NULL DEFAULT false,
  quantity integer NOT NULL DEFAULT 1,
  stock_status text NOT NULL DEFAULT 'IN_STOCK',
  images jsonb NOT NULL DEFAULT '[]'::jsonb,
  barcode text,
  qr_code text,
  delivery_method text NOT NULL DEFAULT '',
  pickup_available boolean NOT NULL DEFAULT false,
  warranty text,
  return_policy text,
  weight_kg numeric,
  dimensions_cm text,
  is_auction boolean NOT NULL DEFAULT false,
  view_count integer NOT NULL DEFAULT 0,
  payment_methods jsonb NOT NULL DEFAULT '[]'::jsonb,
  partial_percent numeric,
  partial_remaining_days integer,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_products_seller_id ON public.products(seller_id);
CREATE INDEX idx_products_business_id ON public.products(business_id);
CREATE INDEX idx_products_category ON public.products(category);
CREATE INDEX idx_products_stock_status ON public.products(stock_status);
CREATE INDEX idx_products_is_auction ON public.products(is_auction);
CREATE INDEX idx_products_created_at ON public.products(created_at DESC);

CREATE TRIGGER products_set_updated_at
  BEFORE UPDATE ON public.products
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- =============================================================================
-- AUCTIONS & BIDS
-- =============================================================================

CREATE TABLE public.auctions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id bigint NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  starting_bid numeric NOT NULL DEFAULT 0,
  reserve_price numeric NOT NULL DEFAULT 0,
  buy_now_price numeric,
  ends_at timestamptz NOT NULL,
  is_active boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_auctions_product_id ON public.auctions(product_id);
CREATE INDEX idx_auctions_is_active ON public.auctions(is_active);
CREATE INDEX idx_auctions_ends_at ON public.auctions(ends_at);

CREATE TABLE public.bids (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  auction_id bigint NOT NULL REFERENCES public.auctions(id) ON DELETE CASCADE,
  user_id bigint NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  username text NOT NULL DEFAULT '',
  user_avatar text NOT NULL DEFAULT '',
  amount numeric NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_bids_auction_id ON public.bids(auction_id);
CREATE INDEX idx_bids_user_id ON public.bids(user_id);
CREATE INDEX idx_bids_created_at ON public.bids(created_at DESC);

-- =============================================================================
-- ORDERS
-- =============================================================================

CREATE TABLE public.orders (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_number text UNIQUE NOT NULL,
  buyer_id bigint NOT NULL REFERENCES public.profiles(id) ON DELETE RESTRICT,
  seller_id bigint NOT NULL REFERENCES public.profiles(id) ON DELETE RESTRICT,
  product_id bigint NOT NULL REFERENCES public.products(id) ON DELETE RESTRICT,
  product_title text NOT NULL DEFAULT '',
  product_image text NOT NULL DEFAULT '',
  total_amount numeric NOT NULL DEFAULT 0,
  discount_amount numeric NOT NULL DEFAULT 0,
  delivery_fee numeric NOT NULL DEFAULT 0,
  tax_amount numeric NOT NULL DEFAULT 0,
  payment_method text NOT NULL DEFAULT '',
  delivery_method text NOT NULL DEFAULT '',
  delivery_address text NOT NULL DEFAULT '',
  delivery_city text NOT NULL DEFAULT '',
  delivery_state text NOT NULL DEFAULT '',
  delivery_lat double precision,
  delivery_lng double precision,
  pickup_lat double precision,
  pickup_lng double precision,
  delivery_pin text NOT NULL DEFAULT '',
  qr_code_token text NOT NULL DEFAULT '',
  status text NOT NULL DEFAULT 'PENDING',
  good_points_used integer NOT NULL DEFAULT 0,
  selected_partner_id bigint,
  service_type text,
  has_good_sale_protect boolean NOT NULL DEFAULT false,
  protect_fee numeric NOT NULL DEFAULT 0,
  deposit_percent numeric,
  deposit_remaining_days integer,
  deposit_amount_paid numeric,
  balance_remaining numeric,
  is_balance_settled boolean NOT NULL DEFAULT false,
  bank_transfer_receipt text,
  invoice_terms text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_orders_buyer_id ON public.orders(buyer_id);
CREATE INDEX idx_orders_seller_id ON public.orders(seller_id);
CREATE INDEX idx_orders_product_id ON public.orders(product_id);
CREATE INDEX idx_orders_status ON public.orders(status);
CREATE INDEX idx_orders_order_number ON public.orders(order_number);
CREATE INDEX idx_orders_created_at ON public.orders(created_at DESC);
CREATE INDEX idx_orders_selected_partner_id ON public.orders(selected_partner_id);

CREATE TRIGGER orders_set_updated_at
  BEFORE UPDATE ON public.orders
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- =============================================================================
-- ESCROWS & DISPUTES
-- =============================================================================

CREATE TABLE public.escrows (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id bigint NOT NULL UNIQUE REFERENCES public.orders(id) ON DELETE CASCADE,
  held_amount numeric NOT NULL DEFAULT 0,
  is_released boolean NOT NULL DEFAULT false,
  is_refunded boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_escrows_order_id ON public.escrows(order_id);
CREATE INDEX idx_escrows_is_released ON public.escrows(is_released);

CREATE TRIGGER escrows_set_updated_at
  BEFORE UPDATE ON public.escrows
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE public.disputes (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id bigint NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
  order_number text NOT NULL DEFAULT '',
  opened_by_id bigint NOT NULL REFERENCES public.profiles(id) ON DELETE RESTRICT,
  opened_by_name text NOT NULL DEFAULT '',
  reason text NOT NULL,
  evidence_url text,
  admin_notes text,
  resolution text NOT NULL DEFAULT 'PENDING',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_disputes_order_id ON public.disputes(order_id);
CREATE INDEX idx_disputes_opened_by_id ON public.disputes(opened_by_id);
CREATE INDEX idx_disputes_resolution ON public.disputes(resolution);

CREATE TRIGGER disputes_set_updated_at
  BEFORE UPDATE ON public.disputes
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- =============================================================================
-- CHAT
-- =============================================================================

CREATE TABLE public.chat_rooms (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  buyer_id bigint NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  seller_id bigint NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  product_id bigint NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  product_title text NOT NULL DEFAULT '',
  product_price numeric NOT NULL DEFAULT 0,
  product_image text NOT NULL DEFAULT '',
  seller_name text NOT NULL DEFAULT '',
  buyer_name text NOT NULL DEFAULT '',
  last_message text,
  last_message_time timestamptz,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_chat_rooms_buyer_id ON public.chat_rooms(buyer_id);
CREATE INDEX idx_chat_rooms_seller_id ON public.chat_rooms(seller_id);
CREATE INDEX idx_chat_rooms_product_id ON public.chat_rooms(product_id);

CREATE TRIGGER chat_rooms_set_updated_at
  BEFORE UPDATE ON public.chat_rooms
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE public.messages (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_id bigint NOT NULL REFERENCES public.chat_rooms(id) ON DELETE CASCADE,
  sender_id bigint NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  message_text text,
  image_url text,
  video_url text,
  voice_note_url text,
  receipt_details jsonb,
  product_details jsonb,
  offer_details jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_messages_room_id ON public.messages(room_id);
CREATE INDEX idx_messages_sender_id ON public.messages(sender_id);
CREATE INDEX idx_messages_created_at ON public.messages(created_at);

-- =============================================================================
-- REVIEWS
-- =============================================================================

CREATE TABLE public.reviews (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id bigint REFERENCES public.orders(id) ON DELETE SET NULL,
  product_id bigint REFERENCES public.products(id) ON DELETE SET NULL,
  reviewer_id bigint NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  reviewer_name text NOT NULL DEFAULT '',
  reviewer_photo text NOT NULL DEFAULT '',
  reviewee_id bigint REFERENCES public.profiles(id) ON DELETE SET NULL,
  rating integer NOT NULL DEFAULT 0,
  comment text NOT NULL DEFAULT '',
  image_url text,
  seller_reply text,
  is_helpful_votes integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_reviews_order_id ON public.reviews(order_id);
CREATE INDEX idx_reviews_product_id ON public.reviews(product_id);
CREATE INDEX idx_reviews_reviewer_id ON public.reviews(reviewer_id);
CREATE INDEX idx_reviews_reviewee_id ON public.reviews(reviewee_id);

CREATE TABLE public.review_replies (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  review_id bigint NOT NULL REFERENCES public.reviews(id) ON DELETE CASCADE,
  author_id bigint NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  author_name text NOT NULL DEFAULT '',
  author_photo text NOT NULL DEFAULT '',
  author_role text NOT NULL DEFAULT 'BUYER',
  comment text NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_review_replies_review_id ON public.review_replies(review_id);
CREATE INDEX idx_review_replies_author_id ON public.review_replies(author_id);

-- =============================================================================
-- IDENTITY VERIFICATIONS
-- =============================================================================

CREATE TABLE public.identity_verifications (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  full_name text NOT NULL,
  document_type text NOT NULL,
  document_number text NOT NULL,
  document_image_url text NOT NULL DEFAULT '',
  selfie_image_url text NOT NULL DEFAULT '',
  proof_of_address_url text NOT NULL DEFAULT '',
  status text NOT NULL DEFAULT 'PENDING',
  admin_notes text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_identity_verifications_user_id ON public.identity_verifications(user_id);
CREATE INDEX idx_identity_verifications_status ON public.identity_verifications(status);

CREATE TRIGGER identity_verifications_set_updated_at
  BEFORE UPDATE ON public.identity_verifications
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- =============================================================================
-- GOOD POINTS & REFERRALS
-- =============================================================================

CREATE TABLE public.good_points_transactions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  points integer NOT NULL,
  reason text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_good_points_transactions_user_id ON public.good_points_transactions(user_id);
CREATE INDEX idx_good_points_transactions_created_at ON public.good_points_transactions(created_at DESC);

CREATE TABLE public.referrals (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  referrer_id bigint NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  referee_id bigint NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  referee_name text NOT NULL DEFAULT '',
  status text NOT NULL DEFAULT 'REGISTERED',
  points_reward integer NOT NULL DEFAULT 0,
  reward_released boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (referrer_id, referee_id)
);

CREATE INDEX idx_referrals_referrer_id ON public.referrals(referrer_id);
CREATE INDEX idx_referrals_referee_id ON public.referrals(referee_id);
CREATE INDEX idx_referrals_status ON public.referrals(status);

-- =============================================================================
-- NOTIFICATIONS
-- =============================================================================

CREATE TABLE public.notifications (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  title text NOT NULL,
  message text NOT NULL DEFAULT '',
  type text NOT NULL DEFAULT 'ORDER',
  is_read boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_notifications_user_id ON public.notifications(user_id);
CREATE INDEX idx_notifications_is_read ON public.notifications(is_read);
CREATE INDEX idx_notifications_created_at ON public.notifications(created_at DESC);

-- =============================================================================
-- SAFE MEET
-- =============================================================================

CREATE TABLE public.safe_meet_locations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name text NOT NULL,
  address text NOT NULL DEFAULT '',
  lat double precision NOT NULL,
  lng double precision NOT NULL,
  photo_url text NOT NULL DEFAULT '',
  opening_hours text NOT NULL DEFAULT '',
  safety_rating numeric NOT NULL DEFAULT 0,
  distance_km numeric NOT NULL DEFAULT 0,
  travel_time_minutes integer NOT NULL DEFAULT 0,
  parking_available boolean NOT NULL DEFAULT false,
  accessibility text NOT NULL DEFAULT '',
  is_favorite boolean NOT NULL DEFAULT false,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_safe_meet_locations_lat_lng ON public.safe_meet_locations(lat, lng);

CREATE TABLE public.safe_meet_meetups (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id bigint NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
  location_id bigint NOT NULL REFERENCES public.safe_meet_locations(id) ON DELETE RESTRICT,
  scheduled_at timestamptz NOT NULL,
  status text NOT NULL DEFAULT 'PENDING_CONFIRMATION',
  buyer_confirmed_arrival boolean NOT NULL DEFAULT false,
  seller_confirmed_arrival boolean NOT NULL DEFAULT false,
  rating numeric,
  report_text text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_safe_meet_meetups_order_id ON public.safe_meet_meetups(order_id);
CREATE INDEX idx_safe_meet_meetups_location_id ON public.safe_meet_meetups(location_id);
CREATE INDEX idx_safe_meet_meetups_status ON public.safe_meet_meetups(status);

-- =============================================================================
-- FOLLOWERS & BUNDLES
-- =============================================================================

CREATE TABLE public.follower_relations (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  follower_id bigint NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  followed_user_id bigint REFERENCES public.profiles(id) ON DELETE CASCADE,
  followed_business_id bigint REFERENCES public.businesses(id) ON DELETE CASCADE,
  created_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT follower_relations_target_chk CHECK (
    (followed_user_id IS NOT NULL AND followed_business_id IS NULL)
    OR (followed_user_id IS NULL AND followed_business_id IS NOT NULL)
  )
);

CREATE INDEX idx_follower_relations_follower_id ON public.follower_relations(follower_id);
CREATE INDEX idx_follower_relations_followed_user_id ON public.follower_relations(followed_user_id);
CREATE INDEX idx_follower_relations_followed_business_id ON public.follower_relations(followed_business_id);

CREATE TABLE public.product_bundles (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  seller_id bigint NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  title text NOT NULL,
  description text NOT NULL DEFAULT '',
  product_ids jsonb NOT NULL DEFAULT '[]'::jsonb,
  price numeric NOT NULL DEFAULT 0,
  discount_percentage numeric NOT NULL DEFAULT 0,
  quantity integer NOT NULL DEFAULT 1,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_product_bundles_seller_id ON public.product_bundles(seller_id);

-- =============================================================================
-- DELIVERY (GoodDispatch)
-- =============================================================================

CREATE TABLE public.delivery_partners (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  full_name text NOT NULL,
  phone text NOT NULL DEFAULT '',
  email text NOT NULL DEFAULT '',
  vehicle_type text NOT NULL DEFAULT 'MOTORCYCLE',
  brand text NOT NULL DEFAULT '',
  model text NOT NULL DEFAULT '',
  plate_number text NOT NULL DEFAULT '',
  color text NOT NULL DEFAULT '',
  year integer,
  capacity text NOT NULL DEFAULT '',
  photo_url text NOT NULL DEFAULT '',
  status text NOT NULL DEFAULT 'PENDING',
  is_available boolean NOT NULL DEFAULT false,
  trust_score numeric NOT NULL DEFAULT 50,
  rating numeric NOT NULL DEFAULT 0,
  completed_deliveries integer NOT NULL DEFAULT 0,
  acceptance_rate numeric NOT NULL DEFAULT 0,
  active_deliveries_count integer NOT NULL DEFAULT 0,
  address text NOT NULL DEFAULT '',
  state text NOT NULL DEFAULT '',
  city text NOT NULL DEFAULT '',
  last_lat double precision,
  last_lng double precision,
  last_location_at timestamptz,
  nin text NOT NULL DEFAULT '',
  selfie_url text NOT NULL DEFAULT '',
  license_url text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_delivery_partners_user_id ON public.delivery_partners(user_id);
CREATE INDEX idx_delivery_partners_status ON public.delivery_partners(status);
CREATE INDEX idx_delivery_partners_is_available ON public.delivery_partners(is_available);
CREATE INDEX idx_delivery_partners_city ON public.delivery_partners(city);
CREATE INDEX idx_delivery_partners_last_lat_lng ON public.delivery_partners(last_lat, last_lng)
  WHERE last_lat IS NOT NULL AND last_lng IS NOT NULL;

CREATE TRIGGER delivery_partners_set_updated_at
  BEFORE UPDATE ON public.delivery_partners
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- FK from orders.selected_partner_id after delivery_partners exists
ALTER TABLE public.orders
  ADD CONSTRAINT orders_selected_partner_id_fkey
  FOREIGN KEY (selected_partner_id) REFERENCES public.delivery_partners(id) ON DELETE SET NULL;

CREATE TABLE public.delivery_jobs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id bigint NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
  partner_id bigint REFERENCES public.delivery_partners(id) ON DELETE SET NULL,
  status text NOT NULL DEFAULT 'PENDING',
  service_type text NOT NULL DEFAULT 'STANDARD',
  delivery_fee numeric NOT NULL DEFAULT 0,
  platform_commission numeric NOT NULL DEFAULT 0,
  courier_earnings numeric NOT NULL DEFAULT 0,
  est_pickup_time timestamptz,
  est_delivery_time timestamptz,
  current_lat double precision,
  current_lng double precision,
  current_speed numeric,
  pin text NOT NULL DEFAULT '',
  sos_triggered boolean NOT NULL DEFAULT false,
  incident_report text,
  tracking_history jsonb NOT NULL DEFAULT '[]'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_delivery_jobs_order_id ON public.delivery_jobs(order_id);
CREATE INDEX idx_delivery_jobs_partner_id ON public.delivery_jobs(partner_id);
CREATE INDEX idx_delivery_jobs_status ON public.delivery_jobs(status);
CREATE INDEX idx_delivery_jobs_current_lat_lng ON public.delivery_jobs(current_lat, current_lng)
  WHERE current_lat IS NOT NULL AND current_lng IS NOT NULL;

CREATE TRIGGER delivery_jobs_set_updated_at
  BEFORE UPDATE ON public.delivery_jobs
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- =============================================================================
-- REVENUE & ADS
-- =============================================================================

CREATE TABLE public.revenue_settings (
  id bigint PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  escrow_percentage_fee numeric NOT NULL DEFAULT 1.5,
  escrow_min_fee numeric NOT NULL DEFAULT 100,
  escrow_max_fee numeric NOT NULL DEFAULT 15000,
  delivery_commission_percentage numeric NOT NULL DEFAULT 10,
  featured_3_days_price numeric NOT NULL DEFAULT 2500,
  featured_7_days_price numeric NOT NULL DEFAULT 5000,
  featured_14_days_price numeric NOT NULL DEFAULT 9000,
  featured_30_days_price numeric NOT NULL DEFAULT 18000,
  sub_pro_price numeric NOT NULL DEFAULT 15000,
  sub_premium_price numeric NOT NULL DEFAULT 35000,
  sub_enterprise_price numeric NOT NULL DEFAULT 85000,
  verified_plus_price numeric NOT NULL DEFAULT 10000,
  flash_sale_feature_price numeric NOT NULL DEFAULT 7500,
  auction_success_fee_percentage numeric NOT NULL DEFAULT 2.5,
  ad_cpc_price numeric NOT NULL DEFAULT 150,
  good_sale_protect_fee numeric NOT NULL DEFAULT 1500,
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TRIGGER revenue_settings_set_updated_at
  BEFORE UPDATE ON public.revenue_settings
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE public.sponsored_ads (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  seller_id bigint NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  type text NOT NULL,
  target_id bigint NOT NULL,
  banner_url text,
  title text NOT NULL DEFAULT '',
  status text NOT NULL DEFAULT 'ACTIVE',
  budget numeric NOT NULL DEFAULT 0,
  spent numeric NOT NULL DEFAULT 0,
  clicks integer NOT NULL DEFAULT 0,
  impressions integer NOT NULL DEFAULT 0,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_sponsored_ads_seller_id ON public.sponsored_ads(seller_id);
CREATE INDEX idx_sponsored_ads_status ON public.sponsored_ads(status);
CREATE INDEX idx_sponsored_ads_type ON public.sponsored_ads(type);

CREATE TABLE public.featured_listings (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_id bigint NOT NULL REFERENCES public.products(id) ON DELETE CASCADE,
  seller_id bigint NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  duration_days integer NOT NULL,
  expires_at timestamptz NOT NULL,
  status text NOT NULL DEFAULT 'ACTIVE',
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_featured_listings_product_id ON public.featured_listings(product_id);
CREATE INDEX idx_featured_listings_seller_id ON public.featured_listings(seller_id);
CREATE INDEX idx_featured_listings_status ON public.featured_listings(status);
CREATE INDEX idx_featured_listings_expires_at ON public.featured_listings(expires_at);

-- =============================================================================
-- WALLETS
-- =============================================================================

CREATE TABLE public.wallets (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL UNIQUE REFERENCES public.profiles(id) ON DELETE CASCADE,
  balance numeric NOT NULL DEFAULT 0,
  bank_name text,
  bank_account_name text,
  bank_account_number text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_wallets_user_id ON public.wallets(user_id);

CREATE TRIGGER wallets_set_updated_at
  BEFORE UPDATE ON public.wallets
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE public.wallet_transactions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  wallet_id bigint NOT NULL REFERENCES public.wallets(id) ON DELETE CASCADE,
  amount numeric NOT NULL,
  type text NOT NULL,
  description text NOT NULL DEFAULT '',
  status text NOT NULL DEFAULT 'PENDING',
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_wallet_transactions_wallet_id ON public.wallet_transactions(wallet_id);
CREATE INDEX idx_wallet_transactions_status ON public.wallet_transactions(status);
CREATE INDEX idx_wallet_transactions_type ON public.wallet_transactions(type);
CREATE INDEX idx_wallet_transactions_created_at ON public.wallet_transactions(created_at DESC);

-- =============================================================================
-- AUDIT & SUBSCRIPTIONS
-- =============================================================================

CREATE TABLE public.audit_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint REFERENCES public.profiles(id) ON DELETE SET NULL,
  action text NOT NULL,
  entity_type text NOT NULL DEFAULT '',
  entity_id bigint,
  details text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_audit_logs_user_id ON public.audit_logs(user_id);
CREATE INDEX idx_audit_logs_entity_type ON public.audit_logs(entity_type);
CREATE INDEX idx_audit_logs_created_at ON public.audit_logs(created_at DESC);

CREATE TABLE public.business_subscriptions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  plan text NOT NULL DEFAULT 'FREE',
  expires_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_business_subscriptions_user_id ON public.business_subscriptions(user_id);
CREATE INDEX idx_business_subscriptions_plan ON public.business_subscriptions(plan);
CREATE INDEX idx_business_subscriptions_expires_at ON public.business_subscriptions(expires_at);

CREATE TABLE public.verified_plus_subscriptions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  expires_at timestamptz NOT NULL,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_verified_plus_subscriptions_user_id ON public.verified_plus_subscriptions(user_id);
CREATE INDEX idx_verified_plus_subscriptions_expires_at ON public.verified_plus_subscriptions(expires_at);

-- =============================================================================
-- PAYMENTS
-- =============================================================================

CREATE TABLE public.payment_transactions (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  transaction_id text UNIQUE NOT NULL,
  order_id bigint REFERENCES public.orders(id) ON DELETE SET NULL,
  order_number text,
  buyer_id bigint NOT NULL REFERENCES public.profiles(id) ON DELETE RESTRICT,
  seller_id bigint NOT NULL REFERENCES public.profiles(id) ON DELETE RESTRICT,
  amount numeric NOT NULL DEFAULT 0,
  payment_method text NOT NULL DEFAULT '',
  status text NOT NULL DEFAULT 'PENDING',
  purpose text NOT NULL DEFAULT 'ORDER_PAYMENT',
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_payment_transactions_order_id ON public.payment_transactions(order_id);
CREATE INDEX idx_payment_transactions_buyer_id ON public.payment_transactions(buyer_id);
CREATE INDEX idx_payment_transactions_seller_id ON public.payment_transactions(seller_id);
CREATE INDEX idx_payment_transactions_status ON public.payment_transactions(status);
CREATE INDEX idx_payment_transactions_transaction_id ON public.payment_transactions(transaction_id);

CREATE TABLE public.invoices (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  invoice_number text UNIQUE NOT NULL,
  order_id bigint NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
  buyer_id bigint NOT NULL REFERENCES public.profiles(id) ON DELETE RESTRICT,
  seller_id bigint NOT NULL REFERENCES public.profiles(id) ON DELETE RESTRICT,
  business_id bigint NOT NULL REFERENCES public.businesses(id) ON DELETE RESTRICT,
  amount numeric NOT NULL DEFAULT 0,
  terms text NOT NULL DEFAULT '',
  due_date timestamptz NOT NULL,
  status text NOT NULL DEFAULT 'DRAFT',
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_invoices_order_id ON public.invoices(order_id);
CREATE INDEX idx_invoices_buyer_id ON public.invoices(buyer_id);
CREATE INDEX idx_invoices_seller_id ON public.invoices(seller_id);
CREATE INDEX idx_invoices_business_id ON public.invoices(business_id);
CREATE INDEX idx_invoices_status ON public.invoices(status);

CREATE TRIGGER invoices_set_updated_at
  BEFORE UPDATE ON public.invoices
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE public.refunds (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  refund_number text UNIQUE NOT NULL,
  transaction_id text NOT NULL,
  order_id bigint NOT NULL REFERENCES public.orders(id) ON DELETE CASCADE,
  amount numeric NOT NULL DEFAULT 0,
  reason text NOT NULL DEFAULT '',
  status text NOT NULL DEFAULT 'PENDING',
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_refunds_order_id ON public.refunds(order_id);
CREATE INDEX idx_refunds_transaction_id ON public.refunds(transaction_id);
CREATE INDEX idx_refunds_status ON public.refunds(status);

CREATE TABLE public.withdrawal_requests (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  request_number text UNIQUE NOT NULL,
  user_id bigint NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  amount numeric NOT NULL,
  bank_name text NOT NULL DEFAULT '',
  account_number text NOT NULL DEFAULT '',
  account_name text NOT NULL DEFAULT '',
  bank_code text,
  status text NOT NULL DEFAULT 'PENDING',
  admin_notes text,
  paystack_transfer_code text,
  paystack_reference text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_withdrawal_requests_user_id ON public.withdrawal_requests(user_id);
CREATE INDEX idx_withdrawal_requests_status ON public.withdrawal_requests(status);

CREATE TABLE public.payment_settings (
  id bigint PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  enabled_methods jsonb NOT NULL DEFAULT '["escrow","cod","card","bank","invoice","partial"]'::jsonb,
  cod_max_order_value numeric NOT NULL DEFAULT 500000,
  escrow_fee_percentage numeric NOT NULL DEFAULT 1.5,
  delivery_commission_percentage numeric NOT NULL DEFAULT 10,
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TRIGGER payment_settings_set_updated_at
  BEFORE UPDATE ON public.payment_settings
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

CREATE TABLE public.payment_logs (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id bigint REFERENCES public.profiles(id) ON DELETE SET NULL,
  action text NOT NULL,
  details text NOT NULL DEFAULT '',
  ip_address text NOT NULL DEFAULT '',
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX idx_payment_logs_user_id ON public.payment_logs(user_id);
CREATE INDEX idx_payment_logs_created_at ON public.payment_logs(created_at DESC);

-- =============================================================================
-- ROW LEVEL SECURITY
-- =============================================================================

ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.businesses ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.auctions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.bids ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.escrows ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.disputes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.chat_rooms ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.review_replies ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.identity_verifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.good_points_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.referrals ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.notifications ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.safe_meet_locations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.safe_meet_meetups ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.follower_relations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.product_bundles ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.delivery_partners ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.delivery_jobs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.revenue_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.sponsored_ads ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.featured_listings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.wallets ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.wallet_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.audit_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.business_subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.verified_plus_subscriptions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payment_transactions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.invoices ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.refunds ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.withdrawal_requests ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payment_settings ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.payment_logs ENABLE ROW LEVEL SECURITY;

-- ----- profiles -----
CREATE POLICY profiles_public_read ON public.profiles
  FOR SELECT USING (true);

CREATE POLICY profiles_insert_own ON public.profiles
  FOR INSERT TO authenticated
  WITH CHECK (auth_id = auth.uid());

CREATE POLICY profiles_update_own ON public.profiles
  FOR UPDATE TO authenticated
  USING (auth_id = auth.uid() OR public.is_admin())
  WITH CHECK (auth_id = auth.uid() OR public.is_admin());

-- ----- businesses -----
CREATE POLICY businesses_public_read ON public.businesses
  FOR SELECT USING (true);

CREATE POLICY businesses_owner_insert ON public.businesses
  FOR INSERT TO authenticated
  WITH CHECK (owner_id = public.current_profile_id() OR public.is_admin());

CREATE POLICY businesses_owner_update ON public.businesses
  FOR UPDATE TO authenticated
  USING (owner_id = public.current_profile_id() OR public.is_admin())
  WITH CHECK (owner_id = public.current_profile_id() OR public.is_admin());

CREATE POLICY businesses_owner_delete ON public.businesses
  FOR DELETE TO authenticated
  USING (owner_id = public.current_profile_id() OR public.is_admin());

-- ----- products -----
CREATE POLICY products_public_read ON public.products
  FOR SELECT USING (true);

CREATE POLICY products_seller_insert ON public.products
  FOR INSERT TO authenticated
  WITH CHECK (seller_id = public.current_profile_id() OR public.is_admin());

CREATE POLICY products_seller_update ON public.products
  FOR UPDATE TO authenticated
  USING (seller_id = public.current_profile_id() OR public.is_admin())
  WITH CHECK (seller_id = public.current_profile_id() OR public.is_admin());

CREATE POLICY products_seller_delete ON public.products
  FOR DELETE TO authenticated
  USING (seller_id = public.current_profile_id() OR public.is_admin());

-- ----- auctions -----
CREATE POLICY auctions_public_read ON public.auctions
  FOR SELECT USING (true);

CREATE POLICY auctions_seller_insert ON public.auctions
  FOR INSERT TO authenticated
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.products p
      WHERE p.id = product_id AND p.seller_id = public.current_profile_id()
    )
    OR public.is_admin()
  );

CREATE POLICY auctions_seller_update ON public.auctions
  FOR UPDATE TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.products p
      WHERE p.id = product_id AND p.seller_id = public.current_profile_id()
    )
    OR public.is_admin()
  );

CREATE POLICY auctions_seller_delete ON public.auctions
  FOR DELETE TO authenticated
  USING (
    EXISTS (
      SELECT 1 FROM public.products p
      WHERE p.id = product_id AND p.seller_id = public.current_profile_id()
    )
    OR public.is_admin()
  );

-- ----- bids -----
CREATE POLICY bids_public_read ON public.bids
  FOR SELECT USING (true);

CREATE POLICY bids_auth_insert ON public.bids
  FOR INSERT TO authenticated
  WITH CHECK (user_id = public.current_profile_id());

-- ----- orders -----
CREATE POLICY orders_participants_read ON public.orders
  FOR SELECT TO authenticated
  USING (
    buyer_id = public.current_profile_id()
    OR seller_id = public.current_profile_id()
    OR public.is_admin()
  );

CREATE POLICY orders_buyer_insert ON public.orders
  FOR INSERT TO authenticated
  WITH CHECK (buyer_id = public.current_profile_id());

CREATE POLICY orders_participants_update ON public.orders
  FOR UPDATE TO authenticated
  USING (
    buyer_id = public.current_profile_id()
    OR seller_id = public.current_profile_id()
    OR public.is_admin()
  )
  WITH CHECK (
    buyer_id = public.current_profile_id()
    OR seller_id = public.current_profile_id()
    OR public.is_admin()
  );

-- ----- escrows -----
CREATE POLICY escrows_participants_read ON public.escrows
  FOR SELECT TO authenticated
  USING (
    public.is_admin()
    OR EXISTS (
      SELECT 1 FROM public.orders o
      WHERE o.id = order_id
        AND (o.buyer_id = public.current_profile_id() OR o.seller_id = public.current_profile_id())
    )
  );

CREATE POLICY escrows_admin_insert ON public.escrows
  FOR INSERT TO authenticated
  WITH CHECK (public.is_admin() OR EXISTS (
    SELECT 1 FROM public.orders o
    WHERE o.id = order_id AND o.buyer_id = public.current_profile_id()
  ));

CREATE POLICY escrows_admin_update ON public.escrows
  FOR UPDATE TO authenticated
  USING (public.is_admin())
  WITH CHECK (public.is_admin());

-- ----- disputes -----
CREATE POLICY disputes_participants_read ON public.disputes
  FOR SELECT TO authenticated
  USING (
    public.is_admin()
    OR opened_by_id = public.current_profile_id()
    OR EXISTS (
      SELECT 1 FROM public.orders o
      WHERE o.id = order_id
        AND (o.buyer_id = public.current_profile_id() OR o.seller_id = public.current_profile_id())
    )
  );

CREATE POLICY disputes_participants_insert ON public.disputes
  FOR INSERT TO authenticated
  WITH CHECK (
    opened_by_id = public.current_profile_id()
    AND EXISTS (
      SELECT 1 FROM public.orders o
      WHERE o.id = order_id
        AND (o.buyer_id = public.current_profile_id() OR o.seller_id = public.current_profile_id())
    )
  );

CREATE POLICY disputes_admin_update ON public.disputes
  FOR UPDATE TO authenticated
  USING (public.is_admin() OR opened_by_id = public.current_profile_id())
  WITH CHECK (public.is_admin() OR opened_by_id = public.current_profile_id());

-- ----- chat_rooms -----
CREATE POLICY chat_rooms_participants_read ON public.chat_rooms
  FOR SELECT TO authenticated
  USING (
    buyer_id = public.current_profile_id()
    OR seller_id = public.current_profile_id()
    OR public.is_admin()
  );

CREATE POLICY chat_rooms_participants_insert ON public.chat_rooms
  FOR INSERT TO authenticated
  WITH CHECK (
    buyer_id = public.current_profile_id()
    OR seller_id = public.current_profile_id()
  );

CREATE POLICY chat_rooms_participants_update ON public.chat_rooms
  FOR UPDATE TO authenticated
  USING (
    buyer_id = public.current_profile_id()
    OR seller_id = public.current_profile_id()
    OR public.is_admin()
  );

-- ----- messages -----
CREATE POLICY messages_participants_read ON public.messages
  FOR SELECT TO authenticated
  USING (
    public.is_admin()
    OR EXISTS (
      SELECT 1 FROM public.chat_rooms r
      WHERE r.id = room_id
        AND (r.buyer_id = public.current_profile_id() OR r.seller_id = public.current_profile_id())
    )
  );

CREATE POLICY messages_participants_insert ON public.messages
  FOR INSERT TO authenticated
  WITH CHECK (
    sender_id = public.current_profile_id()
    AND EXISTS (
      SELECT 1 FROM public.chat_rooms r
      WHERE r.id = room_id
        AND (r.buyer_id = public.current_profile_id() OR r.seller_id = public.current_profile_id())
    )
  );

-- ----- reviews -----
CREATE POLICY reviews_public_read ON public.reviews
  FOR SELECT USING (true);

CREATE POLICY reviews_auth_insert ON public.reviews
  FOR INSERT TO authenticated
  WITH CHECK (reviewer_id = public.current_profile_id());

CREATE POLICY reviews_owner_update ON public.reviews
  FOR UPDATE TO authenticated
  USING (
    reviewer_id = public.current_profile_id()
    OR reviewee_id = public.current_profile_id()
    OR public.is_admin()
  );

CREATE POLICY reviews_owner_delete ON public.reviews
  FOR DELETE TO authenticated
  USING (reviewer_id = public.current_profile_id() OR public.is_admin());

-- ----- review_replies -----
CREATE POLICY review_replies_public_read ON public.review_replies
  FOR SELECT USING (true);

CREATE POLICY review_replies_auth_insert ON public.review_replies
  FOR INSERT TO authenticated
  WITH CHECK (author_id = public.current_profile_id());

CREATE POLICY review_replies_author_delete ON public.review_replies
  FOR DELETE TO authenticated
  USING (author_id = public.current_profile_id() OR public.is_admin());

-- ----- identity_verifications -----
CREATE POLICY identity_verifications_own_read ON public.identity_verifications
  FOR SELECT TO authenticated
  USING (user_id = public.current_profile_id() OR public.is_admin());

CREATE POLICY identity_verifications_own_insert ON public.identity_verifications
  FOR INSERT TO authenticated
  WITH CHECK (user_id = public.current_profile_id());

CREATE POLICY identity_verifications_admin_update ON public.identity_verifications
  FOR UPDATE TO authenticated
  USING (public.is_admin())
  WITH CHECK (public.is_admin());

-- ----- good_points_transactions -----
CREATE POLICY good_points_own_read ON public.good_points_transactions
  FOR SELECT TO authenticated
  USING (user_id = public.current_profile_id() OR public.is_admin());

CREATE POLICY good_points_admin_insert ON public.good_points_transactions
  FOR INSERT TO authenticated
  WITH CHECK (user_id = public.current_profile_id() OR public.is_admin());

-- ----- referrals -----
CREATE POLICY referrals_own_read ON public.referrals
  FOR SELECT TO authenticated
  USING (
    referrer_id = public.current_profile_id()
    OR referee_id = public.current_profile_id()
    OR public.is_admin()
  );

CREATE POLICY referrals_auth_insert ON public.referrals
  FOR INSERT TO authenticated
  WITH CHECK (
    referrer_id = public.current_profile_id()
    OR referee_id = public.current_profile_id()
    OR public.is_admin()
  );

CREATE POLICY referrals_admin_update ON public.referrals
  FOR UPDATE TO authenticated
  USING (public.is_admin() OR referrer_id = public.current_profile_id())
  WITH CHECK (public.is_admin() OR referrer_id = public.current_profile_id());

-- ----- notifications -----
CREATE POLICY notifications_own_read ON public.notifications
  FOR SELECT TO authenticated
  USING (user_id = public.current_profile_id() OR public.is_admin());

CREATE POLICY notifications_own_update ON public.notifications
  FOR UPDATE TO authenticated
  USING (user_id = public.current_profile_id())
  WITH CHECK (user_id = public.current_profile_id());

CREATE POLICY notifications_insert ON public.notifications
  FOR INSERT TO authenticated
  WITH CHECK (true);

CREATE POLICY notifications_own_delete ON public.notifications
  FOR DELETE TO authenticated
  USING (user_id = public.current_profile_id() OR public.is_admin());

-- ----- safe_meet_locations -----
CREATE POLICY safe_meet_locations_public_read ON public.safe_meet_locations
  FOR SELECT USING (true);

CREATE POLICY safe_meet_locations_admin_write ON public.safe_meet_locations
  FOR ALL TO authenticated
  USING (public.is_admin())
  WITH CHECK (public.is_admin());

-- ----- safe_meet_meetups -----
CREATE POLICY safe_meet_meetups_participants_read ON public.safe_meet_meetups
  FOR SELECT TO authenticated
  USING (
    public.is_admin()
    OR EXISTS (
      SELECT 1 FROM public.orders o
      WHERE o.id = order_id
        AND (o.buyer_id = public.current_profile_id() OR o.seller_id = public.current_profile_id())
    )
  );

CREATE POLICY safe_meet_meetups_participants_insert ON public.safe_meet_meetups
  FOR INSERT TO authenticated
  WITH CHECK (
    EXISTS (
      SELECT 1 FROM public.orders o
      WHERE o.id = order_id
        AND (o.buyer_id = public.current_profile_id() OR o.seller_id = public.current_profile_id())
    )
  );

CREATE POLICY safe_meet_meetups_participants_update ON public.safe_meet_meetups
  FOR UPDATE TO authenticated
  USING (
    public.is_admin()
    OR EXISTS (
      SELECT 1 FROM public.orders o
      WHERE o.id = order_id
        AND (o.buyer_id = public.current_profile_id() OR o.seller_id = public.current_profile_id())
    )
  );

-- ----- follower_relations -----
CREATE POLICY follower_relations_public_read ON public.follower_relations
  FOR SELECT USING (true);

CREATE POLICY follower_relations_own_insert ON public.follower_relations
  FOR INSERT TO authenticated
  WITH CHECK (follower_id = public.current_profile_id());

CREATE POLICY follower_relations_own_delete ON public.follower_relations
  FOR DELETE TO authenticated
  USING (follower_id = public.current_profile_id());

-- ----- product_bundles -----
CREATE POLICY product_bundles_public_read ON public.product_bundles
  FOR SELECT USING (true);

CREATE POLICY product_bundles_seller_insert ON public.product_bundles
  FOR INSERT TO authenticated
  WITH CHECK (seller_id = public.current_profile_id() OR public.is_admin());

CREATE POLICY product_bundles_seller_update ON public.product_bundles
  FOR UPDATE TO authenticated
  USING (seller_id = public.current_profile_id() OR public.is_admin())
  WITH CHECK (seller_id = public.current_profile_id() OR public.is_admin());

CREATE POLICY product_bundles_seller_delete ON public.product_bundles
  FOR DELETE TO authenticated
  USING (seller_id = public.current_profile_id() OR public.is_admin());

-- ----- delivery_partners -----
CREATE POLICY delivery_partners_public_read ON public.delivery_partners
  FOR SELECT USING (true);

CREATE POLICY delivery_partners_own_insert ON public.delivery_partners
  FOR INSERT TO authenticated
  WITH CHECK (user_id = public.current_profile_id() OR public.is_admin());

CREATE POLICY delivery_partners_own_update ON public.delivery_partners
  FOR UPDATE TO authenticated
  USING (user_id = public.current_profile_id() OR public.is_admin())
  WITH CHECK (user_id = public.current_profile_id() OR public.is_admin());

-- ----- delivery_jobs -----
CREATE POLICY delivery_jobs_participants_read ON public.delivery_jobs
  FOR SELECT TO authenticated
  USING (
    public.is_admin()
    OR EXISTS (
      SELECT 1 FROM public.delivery_partners dp
      WHERE dp.id = partner_id AND dp.user_id = public.current_profile_id()
    )
    OR EXISTS (
      SELECT 1 FROM public.orders o
      WHERE o.id = order_id
        AND (o.buyer_id = public.current_profile_id() OR o.seller_id = public.current_profile_id())
    )
    OR (
      partner_id IS NULL
      AND EXISTS (
        SELECT 1 FROM public.delivery_partners dp
        WHERE dp.user_id = public.current_profile_id() AND dp.status = 'APPROVED'
      )
    )
  );

CREATE POLICY delivery_jobs_insert ON public.delivery_jobs
  FOR INSERT TO authenticated
  WITH CHECK (
    public.is_admin()
    OR EXISTS (
      SELECT 1 FROM public.orders o
      WHERE o.id = order_id
        AND (o.buyer_id = public.current_profile_id() OR o.seller_id = public.current_profile_id())
    )
  );

CREATE POLICY delivery_jobs_participants_update ON public.delivery_jobs
  FOR UPDATE TO authenticated
  USING (
    public.is_admin()
    OR EXISTS (
      SELECT 1 FROM public.delivery_partners dp
      WHERE dp.id = partner_id AND dp.user_id = public.current_profile_id()
    )
    OR EXISTS (
      SELECT 1 FROM public.orders o
      WHERE o.id = order_id
        AND (o.buyer_id = public.current_profile_id() OR o.seller_id = public.current_profile_id())
    )
    OR (
      partner_id IS NULL
      AND EXISTS (
        SELECT 1 FROM public.delivery_partners dp
        WHERE dp.user_id = public.current_profile_id() AND dp.status = 'APPROVED'
      )
    )
  );

-- ----- revenue_settings (singleton) -----
CREATE POLICY revenue_settings_public_read ON public.revenue_settings
  FOR SELECT USING (true);

CREATE POLICY revenue_settings_admin_update ON public.revenue_settings
  FOR UPDATE TO authenticated
  USING (public.is_admin())
  WITH CHECK (public.is_admin());

CREATE POLICY revenue_settings_admin_insert ON public.revenue_settings
  FOR INSERT TO authenticated
  WITH CHECK (public.is_admin());

-- ----- sponsored_ads -----
CREATE POLICY sponsored_ads_public_read ON public.sponsored_ads
  FOR SELECT USING (true);

CREATE POLICY sponsored_ads_seller_insert ON public.sponsored_ads
  FOR INSERT TO authenticated
  WITH CHECK (seller_id = public.current_profile_id() OR public.is_admin());

CREATE POLICY sponsored_ads_seller_update ON public.sponsored_ads
  FOR UPDATE TO authenticated
  USING (seller_id = public.current_profile_id() OR public.is_admin())
  WITH CHECK (seller_id = public.current_profile_id() OR public.is_admin());

CREATE POLICY sponsored_ads_seller_delete ON public.sponsored_ads
  FOR DELETE TO authenticated
  USING (seller_id = public.current_profile_id() OR public.is_admin());

-- ----- featured_listings -----
CREATE POLICY featured_listings_public_read ON public.featured_listings
  FOR SELECT USING (true);

CREATE POLICY featured_listings_seller_insert ON public.featured_listings
  FOR INSERT TO authenticated
  WITH CHECK (seller_id = public.current_profile_id() OR public.is_admin());

CREATE POLICY featured_listings_seller_update ON public.featured_listings
  FOR UPDATE TO authenticated
  USING (seller_id = public.current_profile_id() OR public.is_admin())
  WITH CHECK (seller_id = public.current_profile_id() OR public.is_admin());

CREATE POLICY featured_listings_seller_delete ON public.featured_listings
  FOR DELETE TO authenticated
  USING (seller_id = public.current_profile_id() OR public.is_admin());

-- ----- wallets -----
CREATE POLICY wallets_own_select ON public.wallets
  FOR SELECT TO authenticated
  USING (user_id = public.current_profile_id() OR public.is_admin());

CREATE POLICY wallets_own_insert ON public.wallets
  FOR INSERT TO authenticated
  WITH CHECK (user_id = public.current_profile_id() OR public.is_admin());

CREATE POLICY wallets_own_update ON public.wallets
  FOR UPDATE TO authenticated
  USING (user_id = public.current_profile_id() OR public.is_admin())
  WITH CHECK (user_id = public.current_profile_id() OR public.is_admin());

-- ----- wallet_transactions -----
CREATE POLICY wallet_transactions_own_read ON public.wallet_transactions
  FOR SELECT TO authenticated
  USING (
    public.is_admin()
    OR EXISTS (
      SELECT 1 FROM public.wallets w
      WHERE w.id = wallet_id AND w.user_id = public.current_profile_id()
    )
  );

CREATE POLICY wallet_transactions_own_insert ON public.wallet_transactions
  FOR INSERT TO authenticated
  WITH CHECK (
    public.is_admin()
    OR EXISTS (
      SELECT 1 FROM public.wallets w
      WHERE w.id = wallet_id AND w.user_id = public.current_profile_id()
    )
  );

-- ----- audit_logs -----
CREATE POLICY audit_logs_admin_read ON public.audit_logs
  FOR SELECT TO authenticated
  USING (public.is_admin() OR user_id = public.current_profile_id());

CREATE POLICY audit_logs_insert ON public.audit_logs
  FOR INSERT TO authenticated
  WITH CHECK (user_id = public.current_profile_id() OR public.is_admin());

-- ----- business_subscriptions -----
CREATE POLICY business_subscriptions_own_read ON public.business_subscriptions
  FOR SELECT TO authenticated
  USING (user_id = public.current_profile_id() OR public.is_admin());

CREATE POLICY business_subscriptions_own_insert ON public.business_subscriptions
  FOR INSERT TO authenticated
  WITH CHECK (user_id = public.current_profile_id() OR public.is_admin());

CREATE POLICY business_subscriptions_admin_update ON public.business_subscriptions
  FOR UPDATE TO authenticated
  USING (user_id = public.current_profile_id() OR public.is_admin())
  WITH CHECK (user_id = public.current_profile_id() OR public.is_admin());

-- ----- verified_plus_subscriptions -----
CREATE POLICY verified_plus_own_read ON public.verified_plus_subscriptions
  FOR SELECT TO authenticated
  USING (user_id = public.current_profile_id() OR public.is_admin());

CREATE POLICY verified_plus_own_insert ON public.verified_plus_subscriptions
  FOR INSERT TO authenticated
  WITH CHECK (user_id = public.current_profile_id() OR public.is_admin());

CREATE POLICY verified_plus_admin_update ON public.verified_plus_subscriptions
  FOR UPDATE TO authenticated
  USING (user_id = public.current_profile_id() OR public.is_admin())
  WITH CHECK (user_id = public.current_profile_id() OR public.is_admin());

-- ----- payment_transactions -----
CREATE POLICY payment_transactions_participants_read ON public.payment_transactions
  FOR SELECT TO authenticated
  USING (
    buyer_id = public.current_profile_id()
    OR seller_id = public.current_profile_id()
    OR public.is_admin()
  );

CREATE POLICY payment_transactions_insert ON public.payment_transactions
  FOR INSERT TO authenticated
  WITH CHECK (
    buyer_id = public.current_profile_id()
    OR public.is_admin()
  );

CREATE POLICY payment_transactions_admin_update ON public.payment_transactions
  FOR UPDATE TO authenticated
  USING (public.is_admin())
  WITH CHECK (public.is_admin());

-- ----- invoices -----
CREATE POLICY invoices_participants_read ON public.invoices
  FOR SELECT TO authenticated
  USING (
    buyer_id = public.current_profile_id()
    OR seller_id = public.current_profile_id()
    OR public.is_admin()
  );

CREATE POLICY invoices_seller_insert ON public.invoices
  FOR INSERT TO authenticated
  WITH CHECK (seller_id = public.current_profile_id() OR public.is_admin());

CREATE POLICY invoices_participants_update ON public.invoices
  FOR UPDATE TO authenticated
  USING (
    buyer_id = public.current_profile_id()
    OR seller_id = public.current_profile_id()
    OR public.is_admin()
  );

-- ----- refunds -----
CREATE POLICY refunds_related_read ON public.refunds
  FOR SELECT TO authenticated
  USING (
    public.is_admin()
    OR EXISTS (
      SELECT 1 FROM public.orders o
      WHERE o.id = order_id
        AND (o.buyer_id = public.current_profile_id() OR o.seller_id = public.current_profile_id())
    )
  );

CREATE POLICY refunds_insert ON public.refunds
  FOR INSERT TO authenticated
  WITH CHECK (
    public.is_admin()
    OR EXISTS (
      SELECT 1 FROM public.orders o
      WHERE o.id = order_id AND o.buyer_id = public.current_profile_id()
    )
  );

CREATE POLICY refunds_admin_update ON public.refunds
  FOR UPDATE TO authenticated
  USING (public.is_admin())
  WITH CHECK (public.is_admin());

-- ----- withdrawal_requests -----
CREATE POLICY withdrawal_requests_own_read ON public.withdrawal_requests
  FOR SELECT TO authenticated
  USING (user_id = public.current_profile_id() OR public.is_admin());

CREATE POLICY withdrawal_requests_own_insert ON public.withdrawal_requests
  FOR INSERT TO authenticated
  WITH CHECK (user_id = public.current_profile_id());

CREATE POLICY withdrawal_requests_admin_update ON public.withdrawal_requests
  FOR UPDATE TO authenticated
  USING (public.is_admin() OR user_id = public.current_profile_id())
  WITH CHECK (public.is_admin() OR user_id = public.current_profile_id());

-- ----- payment_settings (singleton) -----
CREATE POLICY payment_settings_public_read ON public.payment_settings
  FOR SELECT USING (true);

CREATE POLICY payment_settings_admin_update ON public.payment_settings
  FOR UPDATE TO authenticated
  USING (public.is_admin())
  WITH CHECK (public.is_admin());

CREATE POLICY payment_settings_admin_insert ON public.payment_settings
  FOR INSERT TO authenticated
  WITH CHECK (public.is_admin());

-- ----- payment_logs -----
CREATE POLICY payment_logs_own_or_admin_read ON public.payment_logs
  FOR SELECT TO authenticated
  USING (user_id = public.current_profile_id() OR public.is_admin());

CREATE POLICY payment_logs_insert ON public.payment_logs
  FOR INSERT TO authenticated
  WITH CHECK (true);

-- =============================================================================
-- REALTIME PUBLICATION
-- =============================================================================

ALTER PUBLICATION supabase_realtime ADD TABLE public.messages;
ALTER PUBLICATION supabase_realtime ADD TABLE public.notifications;
ALTER PUBLICATION supabase_realtime ADD TABLE public.orders;
ALTER PUBLICATION supabase_realtime ADD TABLE public.delivery_jobs;
ALTER PUBLICATION supabase_realtime ADD TABLE public.products;
ALTER PUBLICATION supabase_realtime ADD TABLE public.chat_rooms;
ALTER PUBLICATION supabase_realtime ADD TABLE public.bids;

-- =============================================================================
-- SEED DATA (settings + public safe meet hubs only — no mock users/products)
-- =============================================================================

INSERT INTO public.revenue_settings (
  id,
  escrow_percentage_fee,
  escrow_min_fee,
  escrow_max_fee,
  delivery_commission_percentage,
  featured_3_days_price,
  featured_7_days_price,
  featured_14_days_price,
  featured_30_days_price,
  sub_pro_price,
  sub_premium_price,
  sub_enterprise_price,
  verified_plus_price,
  flash_sale_feature_price,
  auction_success_fee_percentage,
  ad_cpc_price,
  good_sale_protect_fee
) VALUES (
  1,
  1.5,
  100,
  15000,
  10,
  2500,
  5000,
  9000,
  18000,
  15000,
  35000,
  85000,
  10000,
  7500,
  2.5,
  150,
  1500
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.payment_settings (
  id,
  enabled_methods,
  cod_max_order_value,
  escrow_fee_percentage,
  delivery_commission_percentage
) VALUES (
  1,
  '["escrow","cod","card","bank","invoice","partial"]'::jsonb,
  500000,
  1.5,
  10
)
ON CONFLICT (id) DO NOTHING;

INSERT INTO public.safe_meet_locations (
  name, address, lat, lng, photo_url, opening_hours, safety_rating,
  distance_km, travel_time_minutes, parking_available, accessibility, is_favorite
) VALUES
(
  'Ikeja City Mall Public Safe Zone',
  'Obafemi Awolowo Way, Ikeja, Lagos',
  6.5971,
  3.3551,
  'https://picsum.photos/seed/ikejamall/400/250',
  '09:00 AM - 09:00 PM',
  4.9,
  2.3,
  12,
  true,
  'Wheelchair accessible, CCTV monitored, security guard on-site',
  true
),
(
  'GoodSale Hub - Wuse II Partner Center',
  'Adetokunbo Ademola Crescent, Wuse II, Abuja',
  9.0772,
  7.4789,
  'https://picsum.photos/seed/abuja_hub/400/250',
  '08:00 AM - 06:00 PM',
  5.0,
  4.1,
  15,
  true,
  'Private parking lot, biometric security, verified locker access',
  false
),
(
  'Police Station Zone (Wuse Zone 3 Area)',
  'Herbert Macaulay Way, Wuse Zone 3, Abuja',
  9.0664,
  7.4646,
  'https://picsum.photos/seed/policestation/400/250',
  '24 Hours',
  4.8,
  1.2,
  5,
  true,
  'Active police presence, CCTV surveillance, public parking space',
  false
),
(
  'Mega Plaza SafeMeet Partner Cafe',
  'Idowu Martins Street, Victoria Island, Lagos',
  6.4294,
  3.4215,
  'https://picsum.photos/seed/megaplaza/400/250',
  '07:30 AM - 10:00 PM',
  4.7,
  5.8,
  20,
  true,
  'Free WiFi, indoor seating, premium security patrol',
  false
);

-- =============================================================================
-- GRANTS (Supabase roles)
-- =============================================================================

GRANT USAGE ON SCHEMA public TO anon, authenticated, service_role;

GRANT SELECT ON ALL TABLES IN SCHEMA public TO anon, authenticated;
GRANT ALL ON ALL TABLES IN SCHEMA public TO service_role;
GRANT INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA public TO authenticated;

GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO authenticated, service_role;

GRANT EXECUTE ON FUNCTION public.current_profile_id() TO anon, authenticated, service_role;
GRANT EXECUTE ON FUNCTION public.is_admin() TO anon, authenticated, service_role;
