-- =============================================================================
-- 010: Announcements — admin-written popup shown to users on app entry
-- Run AFTER 009_admin_ads.sql
--
-- Admin writes an announcement (update, feature, notice) and it pops up the
-- next time anyone joins or enters the app. Users can dismiss it; dismissing
-- is remembered per device so it never nags twice.
-- =============================================================================

CREATE TABLE IF NOT EXISTS public.announcements (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title      text   NOT NULL DEFAULT '',
  body       text   NOT NULL DEFAULT '',
  kind       text   NOT NULL DEFAULT 'ANNOUNCEMENT',
  audience   text   NOT NULL DEFAULT 'ALL',
  image_url  text   NOT NULL DEFAULT '',
  is_active  boolean NOT NULL DEFAULT true,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_announcements_active ON public.announcements(is_active);

DROP TRIGGER IF EXISTS announcements_set_updated_at ON public.announcements;
CREATE TRIGGER announcements_set_updated_at
  BEFORE UPDATE ON public.announcements
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

-- ---------------------------------------------------------------------------
-- Row Level Security: everyone can read live announcements, only admins write.
-- ---------------------------------------------------------------------------
ALTER TABLE public.announcements ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS announcements_public_read ON public.announcements;
CREATE POLICY announcements_public_read ON public.announcements
  FOR SELECT USING (is_active = true OR public.is_admin());

DROP POLICY IF EXISTS announcements_admin_insert ON public.announcements;
CREATE POLICY announcements_admin_insert ON public.announcements
  FOR INSERT TO authenticated
  WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS announcements_admin_update ON public.announcements;
CREATE POLICY announcements_admin_update ON public.announcements
  FOR UPDATE TO authenticated
  USING (public.is_admin())
  WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS announcements_admin_delete ON public.announcements;
CREATE POLICY announcements_admin_delete ON public.announcements
  FOR DELETE TO authenticated
  USING (public.is_admin());

-- Refresh PostgREST's schema cache.
NOTIFY pgrst, 'reload schema';
