-- =============================================================================
-- 012: Community trust, richer chat, service areas & document review
-- Run AFTER 011_self_service_roles.sql
--
-- Adds:
--   1. messages.reply_to_id            — reply / quote a message in a thread
--   2. message_reactions               — emoji reactions on messages
--   3. calls                           — audio/video call history (WebRTC)
--   4. reports                         — users report users/products/messages
--   5. service_areas                   — admin-managed states/cities GoodSale
--                                        sells in and delivers to
--   6. identity_verifications extras   — application kind, uploaded documents,
--                                        reviewer + rejection reason
--   7. delivery_partners.documents     — extra rider documents as jsonb
--   8. Realtime publication for the new live tables
-- =============================================================================

-- ---------------------------------------------------------------------------
-- 1. Replies
-- ---------------------------------------------------------------------------
ALTER TABLE public.messages
  ADD COLUMN IF NOT EXISTS reply_to_id bigint REFERENCES public.messages(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_messages_reply_to ON public.messages(reply_to_id);

-- ---------------------------------------------------------------------------
-- 2. Reactions
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.message_reactions (
  id         bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  message_id bigint NOT NULL REFERENCES public.messages(id) ON DELETE CASCADE,
  user_id    bigint NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  emoji      text   NOT NULL DEFAULT '👍',
  created_at timestamptz NOT NULL DEFAULT now(),
  UNIQUE (message_id, user_id, emoji)
);

CREATE INDEX IF NOT EXISTS idx_message_reactions_message ON public.message_reactions(message_id);

ALTER TABLE public.message_reactions ENABLE ROW LEVEL SECURITY;

-- Anyone who can read the room's messages can read its reactions.
DROP POLICY IF EXISTS message_reactions_read ON public.message_reactions;
CREATE POLICY message_reactions_read ON public.message_reactions
  FOR SELECT TO authenticated
  USING (
    public.is_admin()
    OR EXISTS (
      SELECT 1 FROM public.messages m
      JOIN public.chat_rooms r ON r.id = m.room_id
      WHERE m.id = message_id
        AND (r.buyer_id = public.current_profile_id() OR r.seller_id = public.current_profile_id())
    )
  );

DROP POLICY IF EXISTS message_reactions_own_insert ON public.message_reactions;
CREATE POLICY message_reactions_own_insert ON public.message_reactions
  FOR INSERT TO authenticated
  WITH CHECK (
    user_id = public.current_profile_id()
    AND EXISTS (
      SELECT 1 FROM public.messages m
      JOIN public.chat_rooms r ON r.id = m.room_id
      WHERE m.id = message_id
        AND (r.buyer_id = public.current_profile_id() OR r.seller_id = public.current_profile_id())
    )
  );

DROP POLICY IF EXISTS message_reactions_own_delete ON public.message_reactions;
CREATE POLICY message_reactions_own_delete ON public.message_reactions
  FOR DELETE TO authenticated
  USING (user_id = public.current_profile_id() OR public.is_admin());

-- ---------------------------------------------------------------------------
-- 3. Calls (audio / video) — history + realtime signalling metadata
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.calls (
  id               bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  room_id          bigint NOT NULL REFERENCES public.chat_rooms(id) ON DELETE CASCADE,
  caller_id        bigint NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  callee_id        bigint NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  kind             text   NOT NULL DEFAULT 'AUDIO',   -- AUDIO | VIDEO
  status           text   NOT NULL DEFAULT 'RINGING', -- RINGING | ONGOING | COMPLETED | MISSED | DECLINED | FAILED
  started_at       timestamptz NOT NULL DEFAULT now(),
  answered_at      timestamptz,
  ended_at         timestamptz,
  duration_seconds integer NOT NULL DEFAULT 0,
  created_at       timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_calls_room ON public.calls(room_id);
CREATE INDEX IF NOT EXISTS idx_calls_caller ON public.calls(caller_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_calls_callee ON public.calls(callee_id, created_at DESC);

ALTER TABLE public.calls ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS calls_participants_read ON public.calls;
CREATE POLICY calls_participants_read ON public.calls
  FOR SELECT TO authenticated
  USING (
    caller_id = public.current_profile_id()
    OR callee_id = public.current_profile_id()
    OR public.is_admin()
  );

-- Either party may open a call record, or update it as it progresses.
DROP POLICY IF EXISTS calls_participants_insert ON public.calls;
CREATE POLICY calls_participants_insert ON public.calls
  FOR INSERT TO authenticated
  WITH CHECK (caller_id = public.current_profile_id() OR public.is_admin());

DROP POLICY IF EXISTS calls_participants_update ON public.calls;
CREATE POLICY calls_participants_update ON public.calls
  FOR UPDATE TO authenticated
  USING (
    caller_id = public.current_profile_id()
    OR callee_id = public.current_profile_id()
    OR public.is_admin()
  )
  WITH CHECK (
    caller_id = public.current_profile_id()
    OR callee_id = public.current_profile_id()
    OR public.is_admin()
  );

-- ---------------------------------------------------------------------------
-- 4. Reports — users report users / products / messages / businesses
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.reports (
  id            bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  reporter_id   bigint REFERENCES public.profiles(id) ON DELETE SET NULL,
  target_type   text   NOT NULL DEFAULT 'USER',  -- USER | PRODUCT | MESSAGE | BUSINESS | ORDER
  target_id     bigint NOT NULL DEFAULT 0,
  target_label  text   NOT NULL DEFAULT '',
  reason        text   NOT NULL DEFAULT '',
  details       text   NOT NULL DEFAULT '',
  evidence_url  text   NOT NULL DEFAULT '',
  status        text   NOT NULL DEFAULT 'OPEN',  -- OPEN | REVIEWING | RESOLVED | DISMISSED
  admin_notes   text,
  resolved_by   bigint REFERENCES public.profiles(id) ON DELETE SET NULL,
  resolved_at   timestamptz,
  created_at    timestamptz NOT NULL DEFAULT now(),
  updated_at    timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_reports_status ON public.reports(status);
CREATE INDEX IF NOT EXISTS idx_reports_target ON public.reports(target_type, target_id);

DROP TRIGGER IF EXISTS reports_set_updated_at ON public.reports;
CREATE TRIGGER reports_set_updated_at
  BEFORE UPDATE ON public.reports
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.reports ENABLE ROW LEVEL SECURITY;

-- Reporters see their own reports; admins see everything.
DROP POLICY IF EXISTS reports_own_read ON public.reports;
CREATE POLICY reports_own_read ON public.reports
  FOR SELECT TO authenticated
  USING (reporter_id = public.current_profile_id() OR public.is_admin());

DROP POLICY IF EXISTS reports_own_insert ON public.reports;
CREATE POLICY reports_own_insert ON public.reports
  FOR INSERT TO authenticated
  WITH CHECK (reporter_id = public.current_profile_id());

DROP POLICY IF EXISTS reports_admin_update ON public.reports;
CREATE POLICY reports_admin_update ON public.reports
  FOR UPDATE TO authenticated
  USING (public.is_admin())
  WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS reports_admin_delete ON public.reports;
CREATE POLICY reports_admin_delete ON public.reports
  FOR DELETE TO authenticated
  USING (public.is_admin());

-- ---------------------------------------------------------------------------
-- 5. Service areas — where GoodSale sells and delivers
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS public.service_areas (
  id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  state          text   NOT NULL,
  city           text   NOT NULL,
  sales_enabled  boolean NOT NULL DEFAULT true,  -- can list / buy here
  delivery_enabled boolean NOT NULL DEFAULT true, -- couriers accept deliveries here
  created_at     timestamptz NOT NULL DEFAULT now(),
  updated_at     timestamptz NOT NULL DEFAULT now(),
  UNIQUE (state, city)
);

CREATE INDEX IF NOT EXISTS idx_service_areas_state ON public.service_areas(state);

DROP TRIGGER IF EXISTS service_areas_set_updated_at ON public.service_areas;
CREATE TRIGGER service_areas_set_updated_at
  BEFORE UPDATE ON public.service_areas
  FOR EACH ROW EXECUTE FUNCTION public.set_updated_at();

ALTER TABLE public.service_areas ENABLE ROW LEVEL SECURITY;

-- Public read: the whole app renders its state/city pickers from this table.
DROP POLICY IF EXISTS service_areas_public_read ON public.service_areas;
CREATE POLICY service_areas_public_read ON public.service_areas
  FOR SELECT USING (true);

DROP POLICY IF EXISTS service_areas_admin_insert ON public.service_areas;
CREATE POLICY service_areas_admin_insert ON public.service_areas
  FOR INSERT TO authenticated
  WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS service_areas_admin_update ON public.service_areas;
CREATE POLICY service_areas_admin_update ON public.service_areas
  FOR UPDATE TO authenticated
  USING (public.is_admin())
  WITH CHECK (public.is_admin());

DROP POLICY IF EXISTS service_areas_admin_delete ON public.service_areas;
CREATE POLICY service_areas_admin_delete ON public.service_areas
  FOR DELETE TO authenticated
  USING (public.is_admin());

-- Seed a sensible Nigerian launch footprint so pickers are never empty.
INSERT INTO public.service_areas (state, city, sales_enabled, delivery_enabled) VALUES
  ('Lagos State', 'Ikeja',        true, true),
  ('Lagos State', 'Lekki',        true, true),
  ('Lagos State', 'Gbagada',      true, true),
  ('Lagos State', 'Yaba',         true, true),
  ('Lagos State', 'Surulere',     true, true),
  ('Lagos State', 'Victoria Island', true, true),
  ('FCT Abuja',   'Abuja CBD',    true, true),
  ('FCT Abuja',   'Garki',        true, true),
  ('FCT Abuja',   'Wuse',         true, true),
  ('Rivers State','Port Harcourt',true, true),
  ('Oyo State',   'Ibadan',       true, true),
  ('Kano State',  'Kano',         true, true),
  ('Enugu State', 'Enugu',        true, true),
  ('Kaduna State','Kaduna',       false, true)
ON CONFLICT (state, city) DO NOTHING;

-- ---------------------------------------------------------------------------
-- 6. Verification applications — richer detail for admins to review
-- ---------------------------------------------------------------------------
ALTER TABLE public.identity_verifications
  ADD COLUMN IF NOT EXISTS application_kind  text NOT NULL DEFAULT 'IDENTITY',
  ADD COLUMN IF NOT EXISTS business_name     text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS business_address  text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS documents         jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS reviewed_by       bigint REFERENCES public.profiles(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS reviewed_at       timestamptz,
  ADD COLUMN IF NOT EXISTS rejection_reason  text NOT NULL DEFAULT '';

CREATE INDEX IF NOT EXISTS idx_identity_verifications_status ON public.identity_verifications(status);

-- Applicants may withdraw / update their own pending application.
DROP POLICY IF EXISTS identity_verifications_own_update ON public.identity_verifications;
CREATE POLICY identity_verifications_own_update ON public.identity_verifications
  FOR UPDATE TO authenticated
  USING (user_id = public.current_profile_id() AND status = 'PENDING')
  WITH CHECK (user_id = public.current_profile_id());

DROP POLICY IF EXISTS identity_verifications_own_delete ON public.identity_verifications;
CREATE POLICY identity_verifications_own_delete ON public.identity_verifications
  FOR DELETE TO authenticated
  USING (user_id = public.current_profile_id() AND status = 'PENDING');

-- ---------------------------------------------------------------------------
-- 7. Rider documents — every uploaded file in one reviewable place
-- ---------------------------------------------------------------------------
ALTER TABLE public.delivery_partners
  ADD COLUMN IF NOT EXISTS documents       jsonb NOT NULL DEFAULT '[]'::jsonb,
  ADD COLUMN IF NOT EXISTS rejection_reason text NOT NULL DEFAULT '',
  ADD COLUMN IF NOT EXISTS reviewed_by     bigint REFERENCES public.profiles(id) ON DELETE SET NULL,
  ADD COLUMN IF NOT EXISTS reviewed_at     timestamptz;

-- ---------------------------------------------------------------------------
-- 8. Realtime — add the newly-live tables to the publication
-- ---------------------------------------------------------------------------
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM pg_publication WHERE pubname = 'supabase_realtime') THEN
    BEGIN
      ALTER PUBLICATION supabase_realtime ADD TABLE public.message_reactions;
    EXCEPTION WHEN duplicate_object THEN NULL;
    END;
    BEGIN
      ALTER PUBLICATION supabase_realtime ADD TABLE public.calls;
    EXCEPTION WHEN duplicate_object THEN NULL;
    END;
    BEGIN
      ALTER PUBLICATION supabase_realtime ADD TABLE public.reports;
    EXCEPTION WHEN duplicate_object THEN NULL;
    END;
    BEGIN
      ALTER PUBLICATION supabase_realtime ADD TABLE public.service_areas;
    EXCEPTION WHEN duplicate_object THEN NULL;
    END;
  END IF;
END $$;

-- Refresh PostgREST's schema cache.
NOTIFY pgrst, 'reload schema';
